{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "sealkeeper.fullname" . }}
  labels:
    {{- include "sealkeeper.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "sealkeeper.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.ingressNamespaceLabel }}
      ports:
        - protocol: TCP
          port: 8443
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- if .Values.networkPolicy.smtp.enabled }}
    - to:
        {{- range .Values.networkPolicy.smtp.cidrs }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
      ports:
        {{- range .Values.networkPolicy.smtp.ports }}
        - protocol: TCP
          port: {{ . }}
        {{- end }}
    {{- end }}
    {{- if .Values.networkPolicy.siem.enabled }}
    - to:
        {{- range .Values.networkPolicy.siem.cidrs }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
      ports:
        {{- range .Values.networkPolicy.siem.ports }}
        - protocol: {{ .protocol }}
          port: {{ .number }}
        {{- end }}
    {{- end }}
{{- end }}
