{{- if and .Values.secret.create (not .Values.secret.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sealkeeper.fullname" . }}
  labels:
    {{- include "sealkeeper.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secret.masterSecret }}
  SK_MASTER_SECRET: {{ .Values.secret.masterSecret | quote }}
  {{- end }}
  {{- if .Values.secret.databaseUrl }}
  SK_DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}
  {{- end }}
  {{- if .Values.secret.metricsToken }}
  SK_METRICS_TOKEN: {{ .Values.secret.metricsToken | quote }}
  {{- end }}
{{- end }}
